CREATE TABLE Topics
(
    Id UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_Topics PRIMARY KEY
        DEFAULT NEWID(),
    Title NVARCHAR(200) NOT NULL,
    Slug NVARCHAR(200) NOT NULL,
    ParentTopicId UNIQUEIDENTIFIER NULL,
    DisplayOrder INT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
    CreatedUtcDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LastModifiedBy UNIQUEIDENTIFIER NULL,
    LastUtcModified DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

ALTER TABLE Topics
ADD CONSTRAINT FK_Topics_Parent
FOREIGN KEY (ParentTopicId)
REFERENCES Topics(Id);

CREATE UNIQUE INDEX UX_Topics_Slug
ON Topics(Slug);

CREATE INDEX IX_Topics_Parent_Display
ON Topics(ParentTopicId, DisplayOrder);
