CREATE TABLE Pages
(
    Id UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_Pages PRIMARY KEY
        DEFAULT NEWID(),
    TopicId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Slug NVARCHAR(200) NOT NULL,
    Summary NVARCHAR(500) NULL,
    IsPublished BIT NOT NULL DEFAULT 0,
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
    CreatedUtcDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LastModifiedBy UNIQUEIDENTIFIER NULL,
    LastUtcModified DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

ALTER TABLE Pages
ADD CONSTRAINT FK_Pages_Topics
FOREIGN KEY (TopicId)
REFERENCES Topics(Id)
ON DELETE CASCADE;

CREATE UNIQUE INDEX UX_Pages_TopicId
ON Pages(TopicId);

CREATE UNIQUE INDEX UX_Pages_Slug
ON Pages(Slug);
